apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.deployName }}
  name: {{ .Values.deployName }}
spec:
  selector:
    app: {{ .Values.deployName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
